name: CI/CD C++ Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Configure and build
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Install Clang
      run: |
        sudo apt-get install -y clang

    - name: Run Clang Static Analyzer
      run: |
        export PATH=$PATH:/usr/lib/llvm-*/bin
        scan-build cmake --build build

    - name: Run cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --quiet --force --inline-suppr --error-exitcode=1 .
