name: CI/CD Code Quality Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: 'CMakeLists.txt'
        cmakeBuildType: 'Release'

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Run Clang static analysis
      run: |
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
        scan-build --status-bugs make

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Check code formatting
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.cpp' '*.h' | xargs clang-format --output-replacements-xml -p 0 | grep -c '<replacement ' > /dev/null

    - name: Run Cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --quiet --force --enable=warning,style,performance,portability --error-exitcode=1 .

    - name: Run CppLint
      run: |
        sudo apt-get install -y python3-pip
        pip3 install cpplint
        cpplint --recursive .

    - name: Run Unit Tests
      run: |
        cd build
        ctest --output-on-failure
