name: CI/CD Code Quality Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build project
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Run static analysis with cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --quiet --enable=all --error-exitcode=1 .

    - name: Run tests and generate coverage
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build
        cmake --build build
        cd build
        ctest
        gcovr -r .. --html-details -o coverage.html

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: build/coverage.html
